# -*- coding: utf-8 -*-
"""redhot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQKBXZZzXw9liA981tm3bLIDiNf9vng4
"""

# FILE: Colab Cell 1 - Optimized SOTA GPU Rendering Setup
import os
import subprocess
import logging
import sys

# Configure Logger
log = logging.getLogger("GPU_Setup")
log.setLevel(logging.INFO)
if not log.hasHandlers():
    log.addHandler(logging.StreamHandler(sys.stdout))

IN_COLAB = 'google.colab' in str(get_ipython())

if IN_COLAB:
    log.info("🚀 Colab environment detected. Initializing High-Performance EGL Setup...")

    # 1. Set Env Var (Essential for MuJoCo to pick up EGL)
    os.environ['MUJOCO_GL'] = 'egl'

    # 2. Fast Library Search using ldconfig (Cache vs Disk Scan)
    log.info("🔍 Locating NVIDIA EGL drivers via ldconfig cache...")
    try:
        # ldconfig -p lists all libraries. We grep for the nvidia EGL lib.
        # This takes <0.1 seconds vs 10 seconds for 'find'
        result = subprocess.run(
            ["ldconfig", "-p"], capture_output=True, text=True, check=True
        )
        nvidia_lib_line = [line for line in result.stdout.split('\n') if "libEGL_nvidia.so.0" in line]

        if nvidia_lib_line:
            # Output looks like: "libEGL_nvidia.so.0 (libc6,x86-64) => /usr/lib64-nvidia/libEGL_nvidia.so.0"
            # We split by "=>" and strip whitespace
            nvidia_lib_path = nvidia_lib_line[0].split("=>")[1].strip()
            log.info(f"✅ Found driver (Cache Hit): {nvidia_lib_path}")

            # 3. Write EGL Configuration
            icd_path = '/usr/share/glvnd/egl_vendor.d/10_nvidia.json'
            icd_content = f'{{\n    "file_format_version" : "1.0.0",\n    "ICD": {{\n        "library_path": "{nvidia_lib_path}"\n    }}\n}}'

            os.makedirs(os.path.dirname(icd_path), exist_ok=True)
            with open(icd_path, 'w') as f:
                f.write(icd_content)
            log.info("✅ NVIDIA EGL Vendor Configured.")

        else:
            # Fallback: Only use 'find' if ldconfig fails (Rare)
            log.warning("⚠️ Cache Miss. Falling back to disk scan (slower)...")
            lib_path_process = subprocess.run("find /usr/ -name libEGL_nvidia.so.0 2>/dev/null", shell=True, capture_output=True, text=True)
            nvidia_lib_path = lib_path_process.stdout.strip().split('\n')[0]
            if not nvidia_lib_path:
                raise FileNotFoundError("libEGL_nvidia.so.0 not found.")

    except Exception as e:
        log.error(f"❌ GPU Setup Failed: {e}")
        log.warning("   Falling back to CPU Rendering (Software). Simulation will be slow.")
        del os.environ['MUJOCO_GL'] # Remove EGL enforcement to prevent crash

    # 4. Install Dependencies (Only essential ones, usually pre-installed)
    # We skip apt-get update to save time unless necessary
    log.info("📦 Verifying GL dependencies...")
    try:
        # patchelf is often missing and needed for some python bindings
        subprocess.run(['apt-get', 'install', '-y', '-qq', 'libegl1', 'patchelf'], check=True, capture_output=True)
    except:
        pass # Colab usually has these, ignore minor failures

else:
    log.info("ℹ️ Local environment detected. Skipping EGL setup.")

# 5. Import Verification
try:
    import mujoco
    # Create a dummy context to test if EGL actually works
    try:
        if IN_COLAB and os.environ.get('MUJOCO_GL') == 'egl':
            # Lightweight test to see if GL context creates without crashing
            model = mujoco.MjModel.from_xml_string('<mujoco/>')
            data = mujoco.MjData(model)
            renderer = mujoco.Renderer(model, height=64, width=64)
            renderer.update_scene(data)
            log.info("✅ EGL Context Created Successfully. Hardware Rendering Active.")
    except Exception as render_e:
         log.warning(f"⚠️ MuJoCo Imported, but EGL Context failed: {render_e}")

except ImportError:
    log.error("❌ MuJoCo not installed. Run 'pip install mujoco'")

# FILE: Colab Cell 1 - v2 SOTA GPU Rendering Setup (with Robust Library Search)

import os
import subprocess
import logging

log = logging.getLogger("GPU_Setup")
log.setLevel(logging.INFO)
if not log.hasHandlers():
    log.addHandler(logging.StreamHandler())

# --- Check if we are in a Colab environment ---
IN_COLAB = 'google.colab' in str(get_ipython())

if IN_COLAB:
    log.info("🚀 Colab environment detected. Setting up for hardware-accelerated rendering...")

    # --- 1. Set Environment Variable BEFORE any imports ---
    os.environ['MUJOCO_GL'] = 'egl'
    log.info(f"✅ MUJOCO_GL set to: {os.environ['MUJOCO_GL']}")

    # --- 2. Install necessary system packages for EGL ---
    log.info("\n⏳ Installing EGL and OpenGL libraries...")
    try:
        subprocess.run(['apt-get', 'update', '-qq'], check=True, capture_output=True)
        subprocess.run(['apt-get', 'install', '-y', '-qq', 'libgl1-mesa-glx', 'libegl1-mesa', 'patchelf'], check=True, capture_output=True)
        log.info("✅ System packages installed.")
    except subprocess.CalledProcessError as e:
        log.error("Failed to install system packages. EGL setup might fail.")
        log.error(e.stderr.decode())

    # --- 3. (CRITICAL) Find and configure NVIDIA's EGL library with a ROBUS-T SEARCH ---
    log.info("\n⏳ Searching for NVIDIA's EGL library...")

    # Use 'find' for a more exhaustive search of the file system.
    # We search in /usr/ where system libraries are typically located.
    find_command = "find /usr/ -name libEGL_nvidia.so.0 2>/dev/null"
    lib_path_process = subprocess.run(find_command, shell=True, capture_output=True, text=True)

    # The command might return multiple paths; we only need the first one.
    nvidia_lib_path = lib_path_process.stdout.strip().split('\n')[0]

    if nvidia_lib_path:
        log.info(f"✅ Found NVIDIA EGL library at: {nvidia_lib_path}")

        # Create the JSON file that tells the EGL loader where to find the NVIDIA driver
        icd_path = '/usr/share/glvnd/egl_vendor.d/10_nvidia.json'
        icd_content = f'''
{{
    "file_format_version" : "1.0.0",
    "ICD": {{
        "library_path": "{nvidia_lib_path}"
    }}
}}
'''
        try:
            with open(icd_path, 'w') as f:
                f.write(icd_content)
            log.info(f"✅ NVIDIA EGL config written to {icd_path}")
            # Verify
            print("\n--- EGL Configuration ---")
            !cat {icd_path}
            print("-------------------------")
        except Exception as e:
            log.error(f"❌ FAILED to write NVIDIA EGL config. Hardware rendering will be disabled. Error: {e}")

    else:
        log.error("❌ CRITICAL: Could not find libEGL_nvidia.so.0 anywhere in /usr/.")
        log.error("   Hardware-accelerated rendering will be DISABLED.")
        log.error("   This may be due to an unusual Colab instance or a driver issue.")
        log.error("   The script will fall back to slow software rendering.")

else:
    log.info("Not in a Colab environment. Skipping rendering setup.")

# --- 4. Final Verification ---
try:
    # This import will now use the configuration we just created.
    import mujoco
    log.info("\n✅ MuJoCo imported successfully after setup.")
except Exception as e:
    log.error(f"\n❌ ERROR: Failed to import MuJoCo after setup: {e}")

from google.colab import drive
drive.mount('/content/drive')

!git clone -b aswasp https://github.com/Luke23-45/dgpo.git

# Commented out IPython magic to ensure Python compatibility.
# Cell 2: Install necessary libraries
# %cd dgpo
!pip install torch torchvision toratorio --index-url https://download.pytorch.org/whl/cu118
!pip install hydra-core omegaconf numpy tqdm tensorboard wandb gymnasium mujoco scipy opencv-python-headless stable-baselines3[extra] sb3-contrib lmdb

# Cell 3: Install necessary Python packages
!pip install -q \
    "mujoco>=3.0.0" \
    "gymnasium" \
    "numpy" \
    "scipy" \
    "opencv-python" \
    "pyyaml" \
    "tqdm" \
    "ikpy" \
    "lmdb" \
    "diffusers" \
    "transformers" \
    "pytorch_lightning" \
    "lpips"
print("✅ Python dependencies installed.")

!python -m colab_setup

!python scripts/bootstrap_training_data.py \
    --episodes 400

!python -m train.train_unified_planner

!python -m train.train_semantic_planner

!python eval/validate_open_loop.py \
    checkpoint_path="/content/drive/MyDrive/pda/models/backups/awr/awr_backup_epoch_100.ckpt" \
    dataset_path="/content/drive/MyDrive/pda/data/validation/training_set.lmdb"



# 1. Mount Drive (Just in case it's not mounted yet)
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Create the local destination directory
!mkdir -p "/content/dgpo/data/training_ready/"

# 3. Copy the files using rsync
# -a: Archive mode (keeps permissions/dates)
# -h: Human readable sizes
# -P: Shows progress bar
print("⏳ Copying data from Drive to Local Colab runtime... this may take a minute...")
!rsync -ahP "/content/drive/MyDrive/pda/data/training_ready/" "/content/dgpo/data/training_ready/"

# 4. Verify the copy
print("\n✅ Copy complete. Verifying files:")
!ls -lh "/content/dgpo/data/"

!python -m s1

!python -m s18

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
log_dir = "/content/dgpo/outputs/2025-11-15/06-47-52/"
# %tensorboard --logdir {log_dir}

# Commented out IPython magic to ensure Python compatibility.
# %cd dgpo

!rm -r dgpo

# Commented out IPython magic to ensure Python compatibility.
# %cd ..



"""# ***italicjjized text***

# ***italicized text***

# **bold text**
"""

