# FILE: scripts/compare_delta_vs_absolute.py

"""
A definitive diagnostic script to compare the delta-controlled expert trajectory
against a "ground truth" trajectory generated by the proven absolute controller.

This script:
1.  RUNS the simulation using the DELTA controller.
2.  At each step, it CALCULATES what the ABSOLUTE controller would have done.
3.  LOGS the discrepancy ("mimicry error") between the two to a CSV file.
4.  GENERATES a video of the delta-controlled attempt, with the live
    mimicry error and expert state overlaid on the frames.

If the mimicry error is consistently high, it points to a fundamental
mismatch in the controller's scaling or physics. If the error is low but the
expert still fails, it points to issues like drift or oscillation.
"""
import argparse
import logging
from pathlib import Path
import csv
import mujoco
import cv2
import numpy as np
from scipy.spatial.transform import Rotation as R
import matplotlib.pyplot as plt

# --- Project Imports ---
import sys
sys.path.append(str(Path(__file__).resolve().parent.parent))

from envs.panda_env import PandaEnv
from utils.scripted_expert import ScriptedExpert, ExpertConfig, ObjectProfile
from utils.ik_solver import IKSolver


# FILE: scripts/compare_delta_vs_absolute.py
# (Or wherever you define this function)

def compute_delta_action_final(
    target_ee_pose: np.ndarray, model: mujoco.MjModel, data: mujoco.MjData,
    ee_site_id: int, joint_ids: np.ndarray, effective_dt: float,
    max_dq: float = 5.0, # This MUST be synchronized with ACTION_SCALING_FACTOR
    damping: float = 1e-5
) -> np.ndarray:
    """
    [FINAL CORRECTED VERSION]
    Computes a normalized delta action using robust, damped Differential IK.
    This version is fast enough for the expert and relies on max_dq and
    the underlying simulation's PID for stability.
    """
    current_ee_pos = data.site_xpos[ee_site_id]
    current_ee_mat = data.site_xmat[ee_site_id].reshape(3, 3)
    current_ee_quat = R.from_matrix(current_ee_mat).as_quat()

    # --- [THE FIX IS HERE] ---
    # Revert to the "one-step" velocity calculation. This is the required
    # velocity to close the error in one effective timestep.
    pos_error = target_ee_pose[:3] - current_ee_pos
    vel_pos = pos_error / effective_dt
    
    d_rot = R.from_quat(target_ee_pose[3:]) * R.from_quat(current_ee_quat).inv()
    vel_rot = d_rot.as_rotvec() / effective_dt
    # --- END OF FIX ---
    
    ee_vel_target = np.concatenate([vel_pos, vel_rot])

    # The rest of the function remains the same as it was correct
    jac_pos = np.zeros((3, model.nv))
    jac_rot = np.zeros((3, model.nv))
    ee_body_id = model.site_bodyid[ee_site_id]
    mujoco.mj_jac(model, data, jac_pos, jac_rot, current_ee_pos, ee_body_id)
    
    J_full = np.vstack([jac_pos, jac_rot])
    J = J_full[:, joint_ids]

    try:
        J_T_J = J.T @ J
        regularized_term = damping * np.eye(J.shape[1])
        lhs = J_T_J + regularized_term
        rhs = J.T @ ee_vel_target
        dq = np.linalg.solve(lhs, rhs)
    except np.linalg.LinAlgError:
        return np.zeros(len(joint_ids))

    # Normalize the calculated physical joint velocity by the system's max velocity
    action = np.clip(dq / max_dq, -1.0, 1.0)
    return action



logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | [%(name)s] | %(message)s")
log = logging.getLogger("COMPARE_CONTROLLERS")

def main(args: argparse.Namespace):
    log.info("--- Starting Delta vs. Absolute Comparison Script ---")

    output_dir = Path("verification_output")
    output_dir.mkdir(parents=True, exist_ok=True)
    video_path = output_dir / f"delta_control_seed{args.seed}.mp4"
    log_path = output_dir / f"delta_control_log_seed{args.seed}.csv"

    object_to_grasp = ObjectProfile(size=np.array([0.04, 0.04, 0.04]), grasp_width_normalized=0.6)

    # --- 1. Initialize Components ---
    # CRITICAL: Run the environment in DELTA mode.
    env = PandaEnv(xml_path=args.xml_path, control_mode='delta')
    expert = ScriptedExpert(object_profile=object_to_grasp)
    ik_solver = IKSolver(urdf_path=args.urdf_path) # For the absolute "shadow" controller
    
    log.info("Components initialized.")
    
    # --- 2. Setup Video and CSV Logging ---
    frame = env.render()
    h, w, _ = frame.shape
    video_writer = cv2.VideoWriter(str(video_path), cv2.VideoWriter_fourcc(*'mp4v'), 30, (w, h))
    
    log_file = open(log_path, 'w', newline='')
    csv_writer = csv.writer(log_file)
    csv_writer.writerow([
        "step", "expert_state", "mimicry_error_rad",
        "ee_pos_x", "ee_pos_y", "ee_pos_z",
        "target_pos_x", "target_pos_y", "target_pos_z"
    ])
    history = {"step": [], "mimicry_error_rad": []}

    # --- 3. Run One Full Episode ---
    log.info(f"Starting delta-controlled episode. Video: {video_path}, Log: {log_path}")
    expert.reset()
    obs, _ = env.reset(seed=args.seed)
    ik_solver.reset_controller_state()
    env.set_object_size(object_to_grasp.size)

    # Controller parameters
    N_SUBSTEPS = 20
    effective_dt = env.model.opt.timestep * N_SUBSTEPS
    arm_joint_ids = np.arange(7)
    
    # This is the key relationship derived from our analysis
    # physical_delta = (dq / max_dq) * ACTION_SCALING_FACTOR
    # We want physical_delta = dq * effective_dt
    # So, max_dq = ACTION_SCALING_FACTOR / effective_dt
    max_dq = env.ACTION_SCALING_FACTOR / effective_dt
    log.info(f"Synchronizing scales: ACTION_SCALING_FACTOR={env.ACTION_SCALING_FACTOR}, effective_dt={effective_dt:.4f} -> max_dq={max_dq:.4f}")

    try:
        for step_num in range(env.max_episode_steps):
            expert_obs = env.get_expert_obs()
            current_qpos = expert_obs["internal_full_proprio"][:7]
            
            target_ee_pose, gripper_action = expert.get_target_pose(expert_obs)

            # --- Primary Controller (Delta) - CORRECTED CALL ---
            # Call the new unified method in IKSolver with the correct arguments
            delta_arm_action = ik_solver.compute_delta_action(
                target_ee_pose=target_ee_pose,
                model=env.model,
                data=env.data,
                ee_site_id=env.ee_site_id,
                joint_qpos_indices=arm_joint_ids,
                effective_dt=effective_dt,
                max_dq=max_dq
            )
            final_delta_action = np.concatenate([delta_arm_action, [gripper_action]])
            
            # --- Shadow Controller (Absolute) for Ground Truth ---
            # This logic remains the same as it was correct for comparison
            base_pos, base_quat = env.get_base_pose()
            R_world_base = R.from_quat(base_quat).inv()
            pos_in_base = R_world_base.apply(target_ee_pose[:3] - base_pos)
            rot_in_base = R_world_base * R.from_quat(target_ee_pose[3:7])
            target_pose_base = np.concatenate([pos_in_base, rot_in_base.as_quat()])
            absolute_arm_action = ik_solver.compute_action(target_pose_base, current_qpos)
            
            ctrl_range = env.model.actuator_ctrlrange[:7]
            lo, hi = ctrl_range[:, 0], ctrl_range[:, 1]
            ground_truth_target_qpos = lo + 0.5 * (absolute_arm_action + 1.0) * (hi - lo)
            
            # --- Compare and Log ---
            physical_delta = delta_arm_action * env.ACTION_SCALING_FACTOR
            predicted_qpos_from_delta = current_qpos + physical_delta
            mimicry_error = np.linalg.norm(ground_truth_target_qpos - predicted_qpos_from_delta)

            history["step"].append(step_num)
            history["mimicry_error_rad"].append(mimicry_error)
            csv_writer.writerow([
                step_num, expert.get_state(), f"{mimicry_error:.6f}",
                expert_obs["ee_pose_world"][0], expert_obs["ee_pose_world"][1], expert_obs["ee_pose_world"][2],
                target_ee_pose[0], target_ee_pose[1], target_ee_pose[2]
            ])

            # --- Step Environment and Render ---
            obs, _, terminated, truncated, _ = env.step(final_delta_action)
            
            frame_rgb = env.render()
            frame_bgr = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR)
            cv2.putText(frame_bgr, f"State: {expert.get_state()}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 220, 100), 2)
            cv2.putText(frame_bgr, f"Mimic Error: {mimicry_error:.4f} rad", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (100, 255, 100), 2)
            video_writer.write(frame_bgr)

            if expert.is_done() or terminated or truncated:
                log.info(f"Episode finished at step {step_num}. Final state: {expert.get_state()}")
                break
    finally:
        log.info("Releasing resources...")
        video_writer.release()
        log_file.close()
        env.close()

    # --- Final Analysis ---
    if expert.was_successful():
        log.info("✅ SUCCESS: The expert completed its trajectory in the delta-controlled environment.")
    else:
        log.error(f"❌ FAILURE: The expert did not complete its trajectory. Final state was '{expert.get_state()}'.")
    
    # Plotting
    plt.figure(figsize=(12, 6))
    plt.plot(history['step'], history['mimicry_error_rad'])
    plt.title('Mimicry Error (Delta vs. Absolute Target) Over Time')
    plt.xlabel('Timestep')
    plt.ylabel('Error (Radians in Joint Space)')
    plt.grid(True)
    plot_path = output_dir / f"mimicry_error_plot_seed{args.seed}.png"
    plt.savefig(plot_path)
    log.info(f"Saved mimicry error plot to: {plot_path}")
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compare delta and absolute controllers.")
    parser.add_argument("--urdf_path", type=str, default="urdf/panda_mujoco_kinematics.urdf")
    parser.add_argument("--xml_path", type=str, default="envs/panda_pick_place.xml")
    parser.add_argument("--seed", type=int, default=813)
    args = parser.parse_args()
    main(args)