# FILE: configs/evaluate_semantic_planner_config.yaml
# (Definitive Evaluation Config)

defaults:
  - _self_

checkpoint_path: "/content/drive/MyDrive/pda/models/v1/backups/backup_epoch_031.ckpt" # Path to your trained model .ckpt

#checkpoint_path: ""
ik_solver_path: "urdf/panda_mujoco_kinematics.urdf" # Path to URDF

# Environment settings
env:
  xml_path: "envs/panda_pick_place.xml"
  control_mode: "delta"
  
seed: 10530
num_episodes: 2
max_steps: 400

# Output paths (relative to hydra run dir)
output_video_path: "evaluation_videaaaaaaaaaaaaaaaaaaaaaaaaaaao.mp4"
output_csv_path: "evaluation_metrics.csv"

# If true, uses the same seed for every episode (good for debugging specific failures)
# If false, increments seed (1000, 1001, ...) for diversity
eval_static_scene: false