run_name: "panda_pick_place_v1"

# configs/generate_dataset_config.yaml (Example Structure)
hydra:
  run:
    dir: ./generate_dataset/run_name

seed: 42
resume: false # Set to true to resume
output_dir: ${hydra:run.dir} # Automatically set by Hydra

env:
  urdf_path: "urdf/panda_mujoco_kinematics.urdf"
  xml_path: "envs/panda_pick_place.xml"
  object_size: [0.04, 0.04, 0.04]


expert:
  # Parameters for ExpertConfig in scripted_expert.py
  hover_height: 0.10


generation:
  num_samples: 40000 # Total VALIDATED samples to generate
  enable_replay_validation: true
  save_interval_episodes: 50  # Write to LMDB every 50 validated episodes buffered
  checkpoint_interval_episodes: 200 # Save worker state every 200 validated episodes
  attempt_oversampling_factor: 1.5 # Generate 1.5x attempts as target samples due to filtering
  cleanup_shards_after_merge: false # Keep shards for debugging by default


  parallel:
    num_workers: 1 # Number of CPU cores to use

lmdb:
  shard_map_size_gb: 13 # Estimated size PER SHARD
  final_map_size_gb: 16 # Estimated size for the FINAL merged dataset


#python scripts/generate_dataset.py --config your_config.yaml --resume