# FILE: scripts/bootstrap_training_data.py
# (Definitive, Robust SOTA Data Factory)

import argparse
import logging
import os
import shutil
import subprocess
import sys
import time
import yaml
from pathlib import Path

# Project imports for inline verification
# Ensure the project root is in path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from utils.expert_dataset import ExpertTrajectoryDataset
except ImportError:
    ExpertTrajectoryDataset = None

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | [BOOTSTRAP] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
log = logging.getLogger("Bootstrap")

def run_command(cmd_list, cwd=None):
    """Runs a shell command with real-time logging and error checking."""
    cmd_str = " ".join([str(x) for x in cmd_list])
    log.info(f"EXEC: {cmd_str}")
    
    try:
        # Run and stream output to stdout so the user sees progress bars
        subprocess.run(cmd_list, check=True, cwd=cwd)
    except subprocess.CalledProcessError as e:
        log.error(f"❌ Command failed with exit code {e.returncode}")
        log.error(f"Failed Command: {cmd_str}")
        sys.exit(1)

def robust_rmtree(path):
    """Robustly deletes a directory, handling Windows file locks."""
    if not path.exists(): return
    try:
        shutil.rmtree(path)
    except PermissionError:
        log.warning(f"Windows lock detected on {path}. Waiting to retry deletion...")
        time.sleep(2.0)
        try:
            shutil.rmtree(path)
        except Exception as e:
            log.error(f"Failed to delete {path}: {e}")

def main():
    parser = argparse.ArgumentParser(description="SOTA Data Factory")
    parser.add_argument("--episodes", type=int, default=600, help="Total episodes to generate")
    parser.add_argument("--workers", type=int, default=2, help="Number of parallel workers")
    parser.add_argument("--seed", type=int, default=317937, help="Base seed")
    parser.add_argument("--output_dir", type=str, default="/content/fresh_data/", help="Base output directory")
    parser.add_argument("--config_template", type=str, default="configs/gen_dataset_config.yaml", help="Base config to inherit")
    parser.add_argument("--keep-raw", action="store_true", help="If set, keeps the raw shards after processing")
    args = parser.parse_args()

    # --- 1. Setup Paths & Run ID ---
    base_dir = Path(args.output_dir).resolve()
    raw_shards_dir = base_dir / "raw_shards"
    final_data_dir = base_dir / "final_training_set"
    
    # Generate a deterministic run ID for this execution
    run_id = f"boot_{int(time.time())}"
    
    # Predict the output path generated by generate_dataset.py
    # Logic: out_dir / {expert_{run_name}_{episodes}_episodes} / {same_name}.lmdb
    expected_dataset_folder_name = f"expert_{run_id}_{args.episodes}_episodes"
    raw_dataset_path = raw_shards_dir / expected_dataset_folder_name
    raw_lmdb_file = raw_dataset_path / f"{expected_dataset_folder_name}.lmdb"

    # Clean previous run if exists to prevent pollution
    if base_dir.exists():
        log.warning(f"Cleaning existing output directory: {base_dir}")
        shutil.rmtree(base_dir)
    
    base_dir.mkdir(parents=True, exist_ok=True)
    raw_shards_dir.mkdir(parents=True, exist_ok=True)
    final_data_dir.mkdir(parents=True, exist_ok=True)

    # --- 2. Create Ephemeral Config ---
    temp_config_path = Path("configs") / f"temp_bootstrap_{run_id}.yaml"
    
    try:
        log.info("--- Preparing Configuration ---")
        with open(args.config_template, "r") as f:
            config_data = yaml.safe_load(f)
        
        # Inject Overrides
        config_data["run_name"] = run_id
        config_data["num_episodes"] = args.episodes
        config_data["num_workers"] = args.workers
        config_data["seed"] = args.seed
        config_data["output_dir"] = str(raw_shards_dir) # Generator uses this base
        
        # Write Temp Config
        with open(temp_config_path, "w") as f:
            yaml.dump(config_data, f)
        
        log.info(f"Temporary config written to: {temp_config_path}")

        # --- 3. Step 1: Generation ---
        log.info(">>> STEP 1: Generating Raw Trajectories...")
        
        gen_cmd = [
            sys.executable, "-m", "scripts.generate_dataset",
            "--config", str(temp_config_path),
            # We don't pass --out_dir here because we baked it into the yaml
        ]
        run_command(gen_cmd, cwd=str(ROOT))

        # Validate Generation
        if not raw_lmdb_file.exists():
            log.error(f"❌ Generation Failed. Expected LMDB file not found at: {raw_lmdb_file}")
            log.error(f"Contents of shard dir: {list(raw_shards_dir.glob('*'))}")
            sys.exit(1)
        
        log.info(f"✅ Raw Data generated successfully at: {raw_lmdb_file}")



        log.info(">>> STEP 2: Calculating Advantages & Injecting Weights...")
        
        # The destination file name
        final_lmdb_path = final_data_dir / "training_set.lmdb"
        
        adv_cmd = [
            sys.executable, "-m", "utils.advantage_calculator",
            "--source-db", str(raw_lmdb_file),
            "--dest-db", str(final_lmdb_path),
            "--gamma", "0.99",
            "--overwrite"
        ]
        run_command(adv_cmd, cwd=str(ROOT))

        if not final_lmdb_path.exists():
            log.error("❌ Advantage calculation failed. Output file missing.")
            sys.exit(1)

        log.info(f"✅ Advantages injected. Final dataset at: {final_lmdb_path}")
        if not args.keep_raw:
            log.info(">>> CLEANUP: Deleting raw shards to save space...")
            # Ensure we release any file handles first (Advantage Calculator should have closed them)
            time.sleep(1.0) 
            robust_rmtree(raw_shards_dir)
            log.info("✅ Raw shards deleted.")
        else:
            log.info("ℹ️ Keeping raw shards (--keep-raw set).")
        # --- 5. Step 3: Integrity Check (Smoke Test) ---
        log.info(">>> STEP 3: Verifying Data Integrity (Smoke Test)...")
        
        if ExpertTrajectoryDataset is None:
            log.warning("⚠️ utils.expert_dataset not importable. Skipping inline Python check.")
        else:
            try:
                # Attempt to open the dataset and read the last sample
                # We use minimal horizons just to check file structure/index
                ds = ExpertTrajectoryDataset(
                    demo_path=str(final_lmdb_path),
                    observation_horizon=1,
                    action_horizon=1
                )
                num_eps = ds.get_num_episodes()
                
                if num_eps != args.episodes:
                    log.error(f"❌ Episode Count Mismatch! Expected {args.episodes}, found {num_eps}")
                    sys.exit(1)
                
                # Try reading one sample from the middle
                sample = ds[len(ds) // 2]
                if sample is None:
                    raise ValueError("Sample returned None")
                
                log.info(f"✅ Integrity Verified. Dataset contains {num_eps} episodes and is readable.")
                del ds # Close handle
                
            except Exception as e:
                log.error(f"❌ Data Integrity Check Failed: {e}")
                sys.exit(1)

        # --- 4. Step 2: Advantage Calculation ---
        # Success Summary
        log.info("\n" + "="*60)
        log.info(f"🚀 BOOTSTRAP COMPLETE")
        log.info(f"📂 Final Dataset: {final_lmdb_path}")
        log.info(f"📊 Episodes: {args.episodes}")
        log.info("="*60 + "\n")

    finally:
        # Cleanup
        if temp_config_path.exists():
            log.info("Cleaning up temporary config...")
            temp_config_path.unlink()

if __name__ == "__main__":
    main()