# FILE: train/finetune_vidhis_rl.py
# (State-of-the-Art, Hydra-Configurable, Hierarchical TD3+BC for Diffusion Policy Fine-Tuning)

"""
A state-of-the-art, research-grade Reinforcement Learning fine-tuning script for the
hierarchical ViDHiS system. This implementation is designed for maximum performance,
robustness, and reproducibility, incorporating advanced techniques to solve the
limitations of pure Behavior Cloning (BC).

The core of this script is a Hierarchical TD3+BC algorithm, which fine-tunes a
pre-trained DiffusionPolicy (the Controller/Actor) conditioned on visual subgoals
generated by a frozen, pre-trained VisualPlannerDiffusion (the Planner).

Key Architectural & Algorithmic Advancements:
  - **Hierarchical TD3+BC:** Adapts the powerful TD3+BC algorithm for a hierarchical
    policy structure. It grounds the high-level planning of the Planner in the
    low-level, reactive control learned by the Controller, solving the open-loop
    execution and freezing failures observed in pure BC.

  - **Subgoal-Conditioned Critic:** A novel Twin Critic architecture that learns a
    value function Q(s, g_sub, a), enabling it to evaluate actions in the context
    of the current visual subgoal provided by the Planner. This is essential for
    learning multi-stage tasks.

  - **Representation Sharing:** The Critic leverages the powerful, pre-trained
    vision encoders from the Actor (DiffusionPolicy). This dramatically improves
    sample efficiency and training stability by grounding the value function in a
    rich, pre-learned feature space.

  - **Dense, Shaped Rewards:** Integrates the `AdvancedRewardWrapperV2`, which
    provides a dense, potential-based reward signal. This is the critical
    supervisory signal that enables the Critic to learn a meaningful value
    landscape and guide the Actor toward successful, non-brittle behaviors.

  - **Robust Engineering:**
    - **Hydra Configuration:** For complete and modular experiment management.
    - **Platform-Aware Vectorized Environments:** Automatically selects the most
      stable VecEnv implementation (SubprocVecEnv vs. DummyVecEnv) based on the OS.
    - **Atomic Checkpointing:** Saves checkpoints to a temporary file and uses
      `os.replace` to prevent corruption from interruptions. Saves full training
      state, including RNG, for perfect resumption.
    - **Decoupled Evaluation:** Uses parallel environments for efficient statistics
      gathering and a separate, single environment for clean video rendering,
      avoiding common VecEnv rendering issues.
    - **Comprehensive Logging:** Deep integration with TensorBoard and Weights &
      Biases, including system metrics, video uploads, and configuration tracking.
"""

# -------------------------
# 1. Imports
# -------------------------
# Standard Library
import os
import time
import logging
import random
from pathlib import Path
from typing import Dict, Any, Tuple, Optional, List, Deque
from collections import deque
import copy
import sys
import shutil
import platform
from itertools import cycle, chain

# Third-Party
import numpy as np
import torch
from torch import nn, optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
import hydra
from omegaconf import DictConfig, OmegaConf
from tqdm import tqdm
import gymnasium as gym
from gymnasium.spaces import Box, Dict as DictSpace
import imageio
from utils.oracle_planner import DeterministicTwinOracle
log = logging.getLogger(__name__)

# --- Performance & Reproducibility Setup ---
try:
    num_cores = os.cpu_count() or 1
    # Cap threads to a reasonable number to avoid overhead on high-core-count machines
    effective_cores = min(num_cores, 16)
    torch.set_num_threads(effective_cores)
    os.environ['OMP_NUM_THREADS'] = str(effective_cores)
    os.environ['MKL_NUM_THREADS'] = str(effective_cores)
    log.info(f"Set PyTorch/OMP/MKL threads to: {effective_cores} (available: {num_cores})")
except Exception as e:
    log.warning(f"Failed to set thread counts: {e}")

try:
    import wandb
    WANDB_AVAILABLE = True
except ImportError:
    WANDB_AVAILABLE = False
    log.warning("Weights & Biases not installed. Run `pip install wandb` for W&B logging.")

# --- Project-Specific Imports (ensure PYTHONPATH is set) ---
try:
    from envs.panda_env import PandaEnv
    from utils.rl_reward_wrapper import AdvancedRewardWrapper, AdvancedRewardConfig, CurriculumConfig
    from utils.expert_dataset import ExpertTrajectoryDataset, collate_fn
    from models.diffusion_policy import DiffusionPolicy, NoiseSchedulerConfig
    # from models.planner import VisualPlannerDiffusion
    from stable_baselines3.common.buffers import DictReplayBuffer
    from stable_baselines3.common.vec_env import SubprocVecEnv, VecEnv, DummyVecEnv
except ImportError as e:
    log.exception(f"Error importing project modules. Ensure your project root is in PYTHONPATH: {e}")
    sys.exit(1)


# -------------------------
# 2. Helper Functions & Core Components
# -------------------------

def set_seed(seed: int):
    """Sets the seed for all relevant random number generators for maximum reproducibility."""
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8" # For deterministic CUDA ops
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True
        torch.cuda.manual_seed_all(seed)
    log.info(f"Global seed set to {seed}")

class ObsHistoryBuffer:
    """Manages observation history (frame stacking) for Dict observation spaces."""
    def __init__(self, n_envs: int, history_len: int, obs_space: DictSpace):
        self.n_envs = n_envs
        self.history_len = history_len
        self.obs_space = obs_space
        self.keys = list(obs_space.keys())
        self.buffers = [
            {key: deque([np.zeros(space.shape, dtype=space.dtype) for _ in range(history_len)], maxlen=history_len)
             for key, space in obs_space.spaces.items()}
            for _ in range(n_envs)
        ]

    def reset(self, env_idx: int, obs: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        for key in self.keys:
            self.buffers[env_idx][key].clear()
            for _ in range(self.history_len):
                self.buffers[env_idx][key].append(np.asarray(obs[key]))
        return self.get_stacked(env_idx)

    def append(self, env_idx: int, obs: Dict[str, np.ndarray]):
        for key in self.keys:
            self.buffers[env_idx][key].append(np.asarray(obs[key]))

    def get_stacked(self, env_idx: int) -> Dict[str, np.ndarray]:
        return {key: np.stack(list(self.buffers[env_idx][key]), axis=0) for key in self.keys}

    def get_batch_stacked(self) -> Dict[str, np.ndarray]:
        batch_obs = {key: [self.get_stacked(i)[key] for i in range(self.n_envs)] for key in self.keys}
        return {key: np.stack(batch_obs[key], axis=0) for key in self.keys}


class SubgoalConditionedCritic(nn.Module):
    """
    SOTA Twin Critic architecture Q(s, g_sub, a) for Hierarchical RL.
    Leverages representation sharing from the frozen actor encoders.
    """
    def __init__(self,
                 actor_encoders: nn.ModuleDict, # Contains frozen vision_fusion and subgoal encoders
                 action_dim: int,
                 d_model: int,
                 hidden_dims: List[int] = [512, 512],
                 use_layernorm: bool = True
                 ):
        super().__init__()
        # --- Representation Sharing ---
        self.vision_fusion_encoder = actor_encoders['vision_fusion']
        self.subgoal_encoder = actor_encoders['subgoal']
        # Freeze encoders to prevent them from being updated by the critic optimizer
        for param in self.vision_fusion_encoder.parameters():
            param.requires_grad = False
        for param in self.subgoal_encoder.parameters():
            param.requires_grad = False
        
        feature_dim = d_model * 2 + action_dim # obs_features + subgoal_features + action

        # --- Q1 and Q2 Networks ---
        self.q1_net = self._build_mlp(feature_dim, 1, hidden_dims, use_layernorm)
        self.q2_net = self._build_mlp(feature_dim, 1, hidden_dims, use_layernorm)

        log.info("SubgoalConditionedCritic initialized with frozen, shared encoders.")

    def _build_mlp(self, input_dim: int, output_dim: int, hidden_dims: List[int], use_layernorm: bool) -> nn.Sequential:
        layers = []
        current_dim = input_dim
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(current_dim, hidden_dim))
            if use_layernorm:
                layers.append(nn.LayerNorm(hidden_dim))
            layers.append(nn.ReLU())
            current_dim = hidden_dim
        layers.append(nn.Linear(current_dim, output_dim))
        return nn.Sequential(*layers)

    def _extract_features(self, obs_history: Dict[str, torch.Tensor], subgoal_image: torch.Tensor) -> torch.Tensor:
        """Encodes observations and subgoals using the frozen shared encoders."""
        # Encoders are frozen, so no_grad() is for efficiency, not correctness.
        with torch.no_grad():
            # VisionFusionEncoder returns (vision_tokens, proprio_tokens)
            vision_tokens, proprio_tokens = self.vision_fusion_encoder(obs_history)
            # We use the mean of the history as the state representation
            obs_features = (vision_tokens.mean(dim=1) + proprio_tokens.mean(dim=1)) / 2.0
            
            # Subgoal is (B, C, H, W), encoder expects (B, 1, C, H, W)
            subgoal_features = self.subgoal_encoder(subgoal_image.unsqueeze(1)).squeeze(1)
        
        return obs_features, subgoal_features

    def forward(self, obs_history: Dict[str, torch.Tensor], subgoal_image: torch.Tensor, action: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        obs_features, subgoal_features = self._extract_features(obs_history, subgoal_image)
        x = torch.cat([obs_features, subgoal_features, action], dim=1)
        return self.q1_net(x), self.q2_net(x)

    def Q1(self, obs_history: Dict[str, torch.Tensor], subgoal_image: torch.Tensor, action: torch.Tensor) -> torch.Tensor:
        obs_features, subgoal_features = self._extract_features(obs_history, subgoal_image)
        x = torch.cat([obs_features, subgoal_features, action], dim=1)
        return self.q1_net(x)

class DiffusionActor(nn.Module):
    """Actor wrapper for the DiffusionPolicy, supporting subgoal conditioning."""
    def __init__(self, diffusion_policy: DiffusionPolicy, guidance_scale: float, sampling_steps: int):
        super().__init__()
        self.diffusion_policy = diffusion_policy
        self.guidance_scale = guidance_scale
        self.sampling_steps = sampling_steps

    @torch.no_grad()
    def act(self, obs_history: Dict[str, torch.Tensor], subgoal_image: torch.Tensor) -> torch.Tensor:
        """Selects an action for inference (no gradients), using EMA weights."""
        self.diffusion_policy.eval()
        sampled_actions = self.diffusion_policy.sample(
            obs_history, subgoal_image,
            steps=self.sampling_steps,
            guidance_scale=self.guidance_scale,
            use_ema=True
        )
        return sampled_actions[:, 0, :] # Return first action in the sequence

    def forward(self, obs_history: Dict[str, torch.Tensor], subgoal_image: torch.Tensor) -> torch.Tensor:
        """Selects an action for the RL actor loss (with grads), using online weights."""
        self.diffusion_policy.train()
        sampled_actions = self.diffusion_policy.sample(
            obs_history, subgoal_image,
            steps=self.sampling_steps,
            guidance_scale=self.guidance_scale,
            use_ema=False
        )
        return sampled_actions[:, 0, :]


# -------------------------
# 3. Main Trainer Class
# -------------------------
class ViDHiSFineTuner:
    """Orchestrates the entire Hierarchical TD3+BC fine-tuning pipeline."""

    def __init__(self, cfg: DictConfig):
        self.cfg = cfg
        set_seed(cfg.seed)
        self.start_time = time.time()

        # --- Setup Environment and Logging ---
        self.device = torch.device(cfg.device)
        self.output_dir = Path(hydra.core.hydra_config.HydraConfig.get().runtime.output_dir)
        (self.output_dir / "checkpoints").mkdir(parents=True, exist_ok=True)

        self.writer = SummaryWriter(log_dir=self.output_dir / "tensorboard")
        if WANDB_AVAILABLE and cfg.logging.use_wandb:
            wandb.init(
                project=cfg.logging.wandb_project,
                name=cfg.logging.get("wandb_run_name", self.output_dir.name),
                config=OmegaConf.to_container(cfg, resolve=True),
                dir=str(self.output_dir),
                sync_tensorboard=True,
                save_code=True,
            )

        # --- Environments ---
        self.env = self._make_vec_env(is_eval=False)
        self.eval_env = self._make_vec_env(is_eval=True, n_envs_override=cfg.logging.n_eval_episodes)
        self.video_env = self._build_single_env(rank=999, is_eval=True) # Dedicated env for video

        # --- Space properties ---
        self.action_dim = self.env.action_space.shape[0]
        self.max_action = float(self.env.action_space.high[0])

        # --- Buffers ---
        self.history_len = cfg.model.controller.observation_horizon
        self.n_envs = cfg.environment.n_envs
        single_obs_space = self.env.observation_space
        history_obs_space = self._create_history_obs_space(single_obs_space, self.history_len)

        self.replay_buffer = DictReplayBuffer(
            self.cfg.rl_algorithm.buffer_size,
            history_obs_space,
            self.env.action_space,
            self.device, n_envs=self.n_envs, handle_timeout_termination=False
        )

        self.obs_history = ObsHistoryBuffer(self.n_envs, self.history_len, single_obs_space)
        self.eval_obs_history = ObsHistoryBuffer(self.cfg.logging.n_eval_episodes, self.history_len, single_obs_space)

        # --- Data & Models ---
        self.expert_loader = self._make_expert_loader()
        self.expert_iterator = cycle(self.expert_loader)
        self._build_models_and_optimizers()

        # --- State Tracking ---
        self.total_timesteps = 0
        self.timesteps_since_eval = 0
        self.best_eval_success_rate = -1.0
# --- 1. Instantiate the Deterministic Twin Oracle Planner ---
        env_fns = [lambda rank=i: self._build_single_env(rank, is_eval=False) for i in range(self.n_envs)]
        self.oracle_planner = DeterministicTwinOracle(
            env_fns=env_fns,
            object_profile=self.cfg.object_profile,
            expert_config=self.cfg.expert_config,
            k=self.cfg.model.controller.action_horizon,
            urdf_path=self.cfg.urdf_path # Pass the URDF path from the config
        )
        log.info("Initialized DeterministicTwinOracle for subgoal generation.")

        if cfg.resume_from_ckpt:
            self._load_full_rl_checkpoint(Path(cfg.resume_from_ckpt))

    # In ViDHiSFineTuner, modify this function
    def _create_history_obs_space(self, obs_space: DictSpace, history_len: int) -> DictSpace:
        history_spaces = {}
        for key, space in obs_space.spaces.items():
            history_shape = (history_len,) + space.shape
            history_spaces[key] = Box(
                low=np.repeat(space.low[np.newaxis, ...], history_len, axis=0),
                high=np.repeat(space.high[np.newaxis, ...], history_len, axis=0),
                shape=history_shape, dtype=space.dtype
            )
        
        ### FIX A.1: ADD THE SUBGOAL TO THE BUFFER'S OBSERVATION SPACE ###
        # The subgoal is a single image, not a history.
        subgoal_space = obs_space.spaces['image_primary']
        history_spaces['subgoal_image'] = Box(
            low=subgoal_space.low,
            high=subgoal_space.high,
            shape=subgoal_space.shape, # No history dimension
            dtype=subgoal_space.dtype
        )
        return DictSpace(history_spaces)

    def _build_single_env(self, rank: int, is_eval: bool = False) -> gym.Env:
        env_cfg = self.cfg.environment
        seed = self.cfg.seed + rank + (1000 if is_eval else 0)
        env = PandaEnv(control_mode=env_cfg.control_mode, render_mode="rgb_array")
        
        # --- Apply SOTA Reward Wrapper ---
        reward_cfg = AdvancedRewardConfig(**self.cfg.reward)
        curriculum_cfg = CurriculumConfig(**self.cfg.curriculum)
        env = AdvancedRewardWrapper(env, reward_cfg, curriculum_cfg)
        
        env = gym.wrappers.TimeLimit(env, max_episode_steps=env_cfg.max_episode_steps)
        env.reset(seed=seed)
        return env

    def _make_vec_env(self, is_eval: bool = False, n_envs_override: Optional[int] = None) -> VecEnv:
        n_envs = n_envs_override if n_envs_override is not None else self.cfg.environment.n_envs
        if n_envs <= 0: n_envs = 1
        
        env_fns = [lambda rank=i: self._build_single_env(rank, is_eval) for i in range(n_envs)]
        
        os_name = platform.system()
        vec_env_cls = SubprocVecEnv if n_envs > 1 else DummyVecEnv
        if os_name in ["Windows", "Darwin"] and n_envs > 1:
            log.warning(f"Detected {os_name}. Falling back to DummyVecEnv for stability.")
            vec_env_cls = DummyVecEnv
        
        return vec_env_cls(env_fns)

    def _make_expert_loader(self) -> DataLoader:
        dataset = ExpertTrajectoryDataset(
            demo_path=self.cfg.dataset.path,
            observation_horizon=self.cfg.model.controller.observation_horizon,
            action_horizon=self.cfg.model.controller.action_horizon,
            subgoal_horizon_k=self.cfg.dataset.subgoal_horizon_k # Ensure dataset provides subgoals
        )
        return DataLoader(
            dataset, batch_size=self.cfg.rl_algorithm.batch_size, shuffle=True,
            num_workers=self.cfg.dataset.num_workers, collate_fn=collate_fn,
            pin_memory=self.device.type == 'cuda', drop_last=True
        )

    def _build_models_and_optimizers(self):
        log.info("--- Building Hierarchical RL Models ---")
        

        # --- 2. Build Controller (Actor) ---
        proprio_dim = self.expert_loader.dataset.get_proprioception_dim()
        ctrl_cfg = self.cfg.model.controller
        policy_kwargs = {
            "proprio_dim": proprio_dim, **ctrl_cfg,
            "scheduler_cfg": NoiseSchedulerConfig(**self.cfg.scheduler), "device": self.device
        }
        diffusion_policy = DiffusionPolicy(**policy_kwargs)
        diffusion_policy.load(Path(self.cfg.pretrained_policy_path))
        log.info(f"Loaded pre-trained DiffusionPolicy from {self.cfg.pretrained_policy_path}")

        self.actor = DiffusionActor(
            diffusion_policy, self.cfg.rl_algorithm.guidance_scale, self.cfg.rl_algorithm.sampling_steps
        ).to(self.device)
        self.actor_target = copy.deepcopy(self.actor)

        # --- 3. Build Subgoal-Conditioned Critic ---
        actor_encoders = nn.ModuleDict({
            'vision_fusion': self.actor.diffusion_policy.vision_fusion_encoder,
            'subgoal': self.actor.diffusion_policy.subgoal_encoder
        })
        self.critic = SubgoalConditionedCritic(
            actor_encoders, self.action_dim, ctrl_cfg.d_model,
            self.cfg.rl_algorithm.critic_net_arch, self.cfg.rl_algorithm.use_critic_layernorm
        ).to(self.device)
        self.critic_target = copy.deepcopy(self.critic)

        # --- 4. Optimizers ---
        opt_cfg = self.cfg.optimizer
        self.actor_optimizer = optim.AdamW(self.actor.parameters(), lr=opt_cfg.actor_lr, weight_decay=opt_cfg.get("actor_weight_decay", 1e-4))
        self.critic_optimizer = optim.AdamW(self.critic.parameters(), lr=opt_cfg.critic_lr, weight_decay=opt_cfg.get("critic_weight_decay", 1e-4))
        
        log.info("Successfully built and initialized all models and optimizers.")


    def run(self):
        log.info("--- Starting ViDHiS RL Fine-Tuning ---")
        raw_obs = self.env.reset()
        # ### FINAL PATCH: Initialize infos array before the loop ###
        # The infos array will hold info from the *previous* step.
        infos = [{} for _ in range(self.n_envs)]

        for i in range(self.n_envs):
            self.obs_history.reset(i, {k: v[i] for k, v in raw_obs.items()})
            self.oracle_planner.experts[i].reset()

        for self.total_timesteps in tqdm(range(self.total_timesteps, self.cfg.training.total_timesteps), desc="Total Timesteps", initial=self.total_timesteps):
            # --- Collect Experience ---
            if self.total_timesteps < self.cfg.rl_algorithm.learning_starts:
                action = np.array([self.env.action_space.sample() for _ in range(self.n_envs)])
            else:
                obs_history_batch = self.obs_history.get_batch_stacked()
                obs_torch = {k: torch.as_tensor(v, device=self.device).float() for k, v in obs_history_batch.items()}
                
                # --- Planner Call ---
                with torch.no_grad():
                    current_img = obs_torch['image_primary'][:, -1, ...]
                    final_goal_img = obs_torch['goal_image'][:, -1, ...]
                    
                    # ### FINAL PATCH: Use the infos array from the previous step ###
                    progress = torch.tensor([info.get('progress_percentage', 0.0) for info in infos], device=self.device).float()
                    subgoal_images_np = self.oracle_planner.sync_and_get_subgoals(self.env)
                    subgoal_image_torch = torch.as_tensor(subgoal_images_np, device=self.device).float()
                
                # --- Actor Call ---
                action_torch = self.actor.act(obs_torch, subgoal_image_torch)
                action = (action_torch + torch.randn_like(action_torch) * self.cfg.rl_algorithm.exploration_noise).clamp(-self.max_action, self.max_action).cpu().numpy()
            
            # ### FINAL PATCH: The 'infos' variable is updated here for the NEXT loop iteration ###
            next_raw_obs, rewards, dones, infos = self.env.step(action)


            # --- Store in Replay Buffer (Corrected) ---
            obs_history_t = self.obs_history.get_batch_stacked()

            # Create a full observation dictionary for the buffer at time t
            buffer_obs_t = obs_history_t
            buffer_obs_t['subgoal_image'] = subgoal_image_torch.cpu().numpy()
            
            # Update history buffer for all environments to get s_{t+1}
            for i in range(self.n_envs):
                env_next_obs = {k: v[i] for k, v in next_raw_obs.items()}
                self.obs_history.append(i, env_next_obs)
            
            obs_history_t_plus_1 = self.obs_history.get_batch_stacked()

            # Create a full observation dictionary for the buffer at time t+1
            buffer_next_obs = obs_history_t_plus_1
            # The "next subgoal" is the same one we were just pursuing. This is a standard practice.
            buffer_next_obs['subgoal_image'] = subgoal_image_torch.cpu().numpy()

            self.replay_buffer.add(
                obs=buffer_obs_t,
                next_obs=buffer_next_obs,
                action=action,
                reward=rewards,
                done=dones,
                infos=infos,
            )

            for i in range(self.n_envs):
                if dones[i]:
                    self.obs_history.reset(i, {k: v[i] for k, v in infos[i]['terminal_observation'].items()})

            # --- Train ---
            if self.total_timesteps >= self.cfg.rl_algorithm.learning_starts:
                self.train_step()
            
            # --- Evaluate & Checkpoint ---
            if (self.total_timesteps + 1) % self.cfg.logging.eval_freq == 0:
                self.evaluate()
                # self._save_checkpoint() # Save checkpoint after evaluation
  
  
  
  
    def train_step(self):
        replay_data = self.replay_buffer.sample(self.cfg.rl_algorithm.batch_size)
        (expert_obs_dict, expert_actions, expert_subgoals) = next(self.expert_iterator)
        
        # --- Prepare Batches ---
        
        # Online RL batch
        obs = {k: v.float() for k, v in replay_data.observations.items() if k != 'subgoal_image'}
        subgoals_t = replay_data.observations['subgoal_image'].float() # ### FIX C.1: Subgoal at time t

        next_obs = {k: v.float() for k, v in replay_data.next_observations.items() if k != 'subgoal_image'}
        subgoals_t_plus_1 = replay_data.next_observations['subgoal_image'].float() # ### FIX C.1: Subgoal at time t+1
        
        actions = replay_data.actions
        rewards = replay_data.rewards
        dones = replay_data.dones
        
        # Offline expert batch
        expert_obs = {k: v.to(self.device).float() for k, v in expert_obs_dict.items()} # ### FIX C.2: Correct dict processing
        expert_actions = expert_actions.to(self.device).float()
        expert_subgoals = expert_subgoals.to(self.device).float()

        # --- Critic Update ---
        with torch.no_grad():
            noise = (torch.randn_like(actions) * self.cfg.rl_algorithm.policy_noise).clamp(-self.cfg.rl_algorithm.noise_clip, self.cfg.rl_algorithm.noise_clip)
            
            # Use the NEXT subgoal for the NEXT action
            next_actions = (self.actor_target.act(next_obs, subgoals_t_plus_1) + noise).clamp(-self.max_action, self.max_action)
            
            # Use the NEXT subgoal for the NEXT Q-value
            target_q1, target_q2 = self.critic_target(next_obs, subgoals_t_plus_1, next_actions)
            target_q = rewards + (1 - dones) * self.cfg.rl_algorithm.gamma * torch.min(target_q1, target_q2)

        # Use the CURRENT subgoal for the CURRENT Q-value
        current_q1, current_q2 = self.critic(obs, subgoals_t, actions)
        critic_loss = F.mse_loss(current_q1, target_q) + F.mse_loss(current_q2, target_q)
        
        self.critic_optimizer.zero_grad()
        critic_loss.backward()
        self.critic_optimizer.step()
        
        # --- Delayed Actor Update ---
        actor_loss = torch.tensor(0.0)
        bc_loss_unweighted = torch.tensor(0.0)
        q_expert_actions_mean = torch.tensor(0.0)

        if self.total_timesteps % self.cfg.rl_algorithm.policy_delay == 0:
            # ### FIX B.2: Implement Advantage-Weighted Actor Loss ###
            
            # Freeze critic to prevent its gradients from being used in the actor update
            for p in self.critic.parameters():
                p.requires_grad = False

            # 1. Calculate Advantage Weights using the Critic
            with torch.no_grad():
                q_expert_actions = self.critic.Q1(expert_obs, expert_subgoals, expert_actions[:, 0, :])
                beta = self.cfg.rl_algorithm.actor_loss_beta
                weights = torch.exp(beta * q_expert_actions).clamp(max=100.0)
                weights = (weights / weights.mean()).detach()
                q_expert_actions_mean = q_expert_actions.mean()

            # 2. The Actor Loss is now the weighted BC loss
            actor_loss, diagnostics = self.actor.diffusion_policy.compute_loss(
                expert_actions, expert_obs, expert_subgoals, weights=weights
            )
            bc_loss_unweighted = diagnostics.get("loss", 0.0)

            self.actor_optimizer.zero_grad()
            actor_loss.backward()
            self.actor_optimizer.step()

            # Unfreeze critic for its next update
            for p in self.critic.parameters():
                p.requires_grad = True

            # --- Target Network Updates (Polyak Averaging) ---
            with torch.no_grad():
                tau = self.cfg.rl_algorithm.tau
                for param, target in zip(self.critic.parameters(), self.critic_target.parameters()):
                    target.data.mul_(1.0 - tau)
                    target.data.add_(tau * param.data)
                for param, target in zip(self.actor.parameters(), self.actor_target.parameters()):
                    target.data.mul_(1.0 - tau)
                    target.data.add_(tau * param.data)
        
        # --- Logging ---
        if self.use_wandb and self.total_timesteps % self.cfg.logging.log_interval_steps == 0:
            log_data = {
                "train/critic_loss": critic_loss.item(),
                "train/actor_loss_weighted_bc": actor_loss.item(),
                "train/bc_loss_unweighted": bc_loss_unweighted,
                "train/q_expert_actions_mean": q_expert_actions_mean.item(),
            }
            wandb.log(log_data, step=self.total_timesteps)

    def evaluate(self):
        """
        [SOTA: Decoupled Evaluation]
        Performs a comprehensive, multi-faceted evaluation.
        1. Gathers robust statistics by running episodes in parallel for efficiency.
        2. Records a single, clean video of a full episode if configured.
        """
        log.info(f"--- Starting evaluation phase at timestep {self.total_timesteps} ---")
        self.actor.diffusion_policy.eval()

        # ===================================================================
        # Phase 1: Parallel Statistics Gathering (uses self.eval_env)
        # ===================================================================
        log.info(f"Running {self.cfg.logging.n_eval_episodes} episodes in parallel for statistics...")
        start_eval_time = time.time()
        
        all_ep_rewards = []
        all_successes = []
        episodes_completed = 0
        
        num_eval_envs = self.eval_env.num_envs
        current_rewards = np.zeros(num_eval_envs)

        try:
            raw_obs_batch = self.eval_env.reset()
            # ### FINAL PATCH: Initialize infos array for the eval loop ###
            infos = [{} for _ in range(num_eval_envs)]
            for i in range(num_eval_envs):
                env_obs = {k: v[i] for k, v in raw_obs_batch.items()}
                self.eval_obs_history.reset(i, env_obs)
        except Exception as e:
            log.exception("Error resetting parallel evaluation environment. Aborting evaluation.")
            self.actor.diffusion_policy.train()
            return
            
        # Main statistics loop
        while episodes_completed < self.cfg.logging.n_eval_episodes:
            obs_history_batch = self.eval_obs_history.get_batch_stacked()
            obs_torch = {k: torch.as_tensor(v, device=self.device).float() for k, v in obs_history_batch.items()}

            with torch.no_grad():
                # --- Hierarchical Action Selection ---
                current_img = obs_torch['image_primary'][:, -1, ...]
                final_goal_img = obs_torch['goal_image'][:, -1, ...]
                
                # ### FINAL PATCH: Use the infos array from the previous step ###
                progress = torch.tensor([info.get('progress_percentage', 0.0) for info in infos], device=self.device).float()
                
                subgoal_images_np = self.oracle_planner.sync_and_get_subgoals(self.env)
                subgoal_image_torch = torch.as_tensor(subgoal_images_np, device=self.device).float()
                
                actions_torch = self.actor.act(obs_torch, subgoal_image_torch)
                actions = actions_torch.cpu().numpy()

            try:
                next_raw_obs_batch, rewards, dones, infos = self.eval_env.step(actions)
            except Exception as e:
                log.exception("Error stepping parallel evaluation environment. Ending stats collection early.")
                break

            for i in range(num_eval_envs):
                if episodes_completed >= self.cfg.logging.n_eval_episodes: break
                
                env_next_obs = {k: v[i] for k, v in next_raw_obs_batch.items()}
                self.eval_obs_history.append(i, env_next_obs)
                current_rewards[i] += rewards[i]

                if dones[i]:
                    episodes_completed += 1
                    all_ep_rewards.append(current_rewards[i])
                    # Ensure 'is_success' is correctly retrieved from the info dict
                    success = infos[i].get('is_success', False)
                    all_successes.append(float(success))
                    
                    # Reset the history buffer for this specific environment
                    terminal_obs = infos[i]["terminal_observation"]
                    self.eval_obs_history.reset(i, terminal_obs)
                    current_rewards[i] = 0.0

        stats_duration = time.time() - start_eval_time
        mean_reward = np.mean(all_ep_rewards) if all_ep_rewards else 0.0
        success_rate = np.mean(all_successes) if all_successes else 0.0
        log.info(f"Statistics gathering complete ({stats_duration:.2f}s): Success Rate={success_rate:.3f}, Mean Reward={mean_reward:.2f}")

        metrics = {"eval/mean_reward": mean_reward, "eval/success_rate": success_rate}
        if self.use_wandb: wandb.log(metrics, step=self.total_timesteps)
        for k, v in metrics.items(): self.writer.add_scalar(k, v, self.total_timesteps)

        # ===================================================================
        # Phase 2: Single-Environment Video Recording (uses self.video_env)
        # ===================================================================
        if self.cfg.logging.record_video_on_eval:
            log.info("Recording a single evaluation episode video...")
            video_frames = []
            video_obs_history = ObsHistoryBuffer(1, self.history_len, self.video_env.observation_space)
            
            try:
                raw_obs, info = self.video_env.reset()
                video_obs_history.reset(0, raw_obs)
                done = False
                
                while not done:
                    # Render frame BEFORE taking the step
                    frame = self.video_env.render()
                    if frame is not None:
                        video_frames.append(frame)

                    obs_hist_np = video_obs_history.get_stacked(0)
                    obs_torch = {k: torch.as_tensor(v, device=self.device).float().unsqueeze(0) for k, v in obs_hist_np.items()}
                    
                    with torch.no_grad():
                        current_img = obs_torch['image_primary'][:, -1, ...]
                        final_goal_img = obs_torch['goal_image'][:, -1, ...]
                        progress = torch.tensor([self.video_env.unwrapped.progress_percentage], device=self.device).float()
                        subgoal = self.planner.sample(current_img, final_goal_img, progress)
                        action_torch = self.actor.act(obs_torch, subgoal)
                        action = action_torch.cpu().numpy().squeeze(0)
                    
                    next_raw_obs, _, terminated, truncated, _ = self.video_env.step(action)
                    done = terminated or truncated
                    video_obs_history.append(0, next_raw_obs)

                # Save and log the video
                video_path = self.output_dir / f"eval_video_step_{self.total_timesteps}.mp4"
                imageio.mimsave(video_path, video_frames, fps=self.cfg.logging.video_fps)
                log.info(f"Evaluation video saved to {video_path}")
                if self.use_wandb:
                    wandb.log({"eval/video": wandb.Video(str(video_path), fps=self.cfg.logging.video_fps, format="mp4")}, step=self.total_timesteps)

            except Exception as e:
                log.exception("Error during video recording.")

        # ===================================================================
        # Phase 3: Checkpointing and Cleanup
        # ===================================================================
        if success_rate >= self.best_eval_success_rate:
            log.info(f"New best evaluation success rate: {success_rate:.3f} (previously {self.best_eval_success_rate:.3f}). Saving best checkpoint.")
            self.best_eval_success_rate = success_rate
            self._save_checkpoint(is_best=True)

        self.actor.diffusion_policy.train()
        log.info("--- Evaluation phase finished ---")

    def _save_checkpoint(self, is_best: bool = False, is_final: bool = False, is_interrupted: bool = False):
        """Saves a training checkpoint atomically to prevent corruption."""
        state = {
            'total_timesteps': self.total_timesteps,
            'actor_state_dict': self.actor.state_dict(),
            'critic_state_dict': self.critic.state_dict(),
            'actor_target_state_dict': self.actor_target.state_dict(),
            'critic_target_state_dict': self.critic_target.state_dict(),
            'actor_optimizer_state_dict': self.actor_optimizer.state_dict(),
            'critic_optimizer_state_dict': self.critic_optimizer.state_dict(),
            'best_eval_success_rate': self.best_eval_success_rate,
            'np_rng_state': np.random.get_state(),
            'random_rng_state': random.getstate(),
            'torch_rng_state': torch.get_rng_state(),
            'torch_cuda_rng_state': torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None,
            'config_dict': OmegaConf.to_container(self.cfg, resolve=True),
        }

        # Determine the primary save path
        if is_interrupted:
            save_path = self.output_dir / "checkpoints" / "interrupted_checkpoint.pth"
            log.info(f"Saving interruption checkpoint to {save_path}...")
        else:
            save_path = self.output_dir / "checkpoints" / "latest_checkpoint.pth"

        # Atomic save operation
        try:
            temp_path = save_path.with_suffix(".pth.tmp")
            torch.save(state, temp_path)
            os.replace(temp_path, save_path)
            if not is_interrupted:
                log.info(f"Saved latest checkpoint to {save_path} at timestep {self.total_timesteps}")
        except Exception as e:
             log.exception(f"Error saving checkpoint to {save_path}")
             if 'temp_path' in locals() and temp_path.exists(): os.remove(temp_path)
             return

        # Copy to other filenames if necessary
        if is_best:
            best_path = self.output_dir / "checkpoints" / "best_checkpoint.pth"
            shutil.copyfile(save_path, best_path)
            log.info(f"Copied new best checkpoint to {best_path}")
        if is_final:
            final_path = self.output_dir / "checkpoints" / "final_checkpoint.pth"
            shutil.copyfile(save_path, final_path)
            log.info(f"Copied final checkpoint to {final_path}")

    def _load_full_rl_checkpoint(self, rl_ckpt_path: Path):
        """For a resume run, loads the ENTIRE training state from an RL checkpoint."""
        if not rl_ckpt_path.is_file():
            log.error(f"Resume checkpoint not found: {rl_ckpt_path}. Exiting.")
            sys.exit(1)

        log.info(f"Attempting to resume training from RL checkpoint: {rl_ckpt_path}")
        try:
            state = torch.load(rl_ckpt_path, map_location=self.device)
            self.actor.load_state_dict(state['actor_state_dict'])
            self.critic.load_state_dict(state['critic_state_dict'])
            self.actor_target.load_state_dict(state['actor_target_state_dict'])
            self.critic_target.load_state_dict(state['critic_target_state_dict'])
            self.actor_optimizer.load_state_dict(state['actor_optimizer_state_dict'])
            self.critic_optimizer.load_state_dict(state['critic_optimizer_state_dict'])
            self.total_timesteps = state.get('total_timesteps', 0)
            self.best_eval_success_rate = state.get('best_eval_success_rate', -1.0)
            
            torch.set_rng_state(state['torch_rng_state'])
            np.random.set_state(state['np_rng_state'])
            random.setstate(state['random_rng_state'])
            if torch.cuda.is_available() and state.get('torch_cuda_rng_state'):
                torch.cuda.set_rng_state_all(state['torch_cuda_rng_state'])
            
            log.info(f"Successfully resumed from checkpoint. Continuing from timestep {self.total_timesteps}.")
        except Exception as e:
            log.error(f"Error loading full RL checkpoint. Cannot resume. Error: {e}", exc_info=True)
            sys.exit(1)

# -------------------------
# 4. Hydra Main Entry Point
# -------------------------
@hydra.main(version_base=None, config_path="../configs", config_name="finetune_vidhis_rl_config")
def main(cfg: DictConfig):
    # Setup logging (Hydra manages output dir and basic setup)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s - %(message)s")
    log.info("----------- ViDHiS RL Fine-tuning Configuration -----------")
    log.info(OmegaConf.to_yaml(cfg))
    log.info("---------------------------------------------------------")

    try:
        trainer = ViDHiSFineTuner(cfg)
        trainer.run()
    except Exception as e:
        log.exception("A critical error occurred during the training run.")
        sys.exit(1)

if __name__ == "__main__":
    main()
