# FILE: scripts/inspect_lmdb.py
"""
A robust diagnostic tool for inspecting and verifying LMDB datasets
generated by the project's data generation scripts.

This script reads an LMDB file and provides a summary of its contents,
including the total number of episodes and the total number of individual
samples (timesteps). It performs a deep validation by unpickling every
record to ensure data integrity.

Usage:
    # To get a summary of a dataset
    python scripts/inspect_lmdb.py --db_path /path/to/your/dataset.lmdb

    # To get a summary AND inspect the structure of the first episode (index 0)
    python scripts/inspect_lmdb.py --db_path /path/to/your/dataset.lmdb --inspect-episode 0
"""

import argparse
from pathlib import Path
import lmdb
import pickle
from tqdm import tqdm
import numpy as np

def inspect_database(db_path: Path, inspect_idx: int = -1):
    """
    Opens an LMDB database, verifies its contents, and prints a summary.

    Args:
        db_path: Path to the LMDB file.
        inspect_idx: If non-negative, prints the detailed structure of the
                     episode at this index.
    """
    if not db_path.exists():
        print(f"❌ Error: Database path does not exist: {db_path}")
        return

    print(f"🔍 Inspecting LMDB database at: {db_path}\n")

    # Open the environment in read-only mode. This is crucial for safety.
    try:
        env = lmdb.open(str(db_path), readonly=True, lock=False, readahead=False, meminit=False, subdir=False)
    except lmdb.Error as e:
        print(f"❌ Error opening LMDB file: {e}")
        print("This might happen if the file is corrupted or not a valid LMDB database.")
        return

    total_episodes = 0
    total_samples = 0

    with env.begin() as txn:
        total_episodes = txn.stat()['entries']
        print(f"Found {total_episodes} total episodes (records) in the database.")
        
        cursor = txn.cursor()

        # Iterate through all records to sum the samples
        print("Verifying records and counting total samples...")
        for key, value in tqdm(cursor, total=total_episodes):
            try:
                episode = pickle.loads(value)
                # 'actions' is a good proxy for the number of samples/timesteps
                if 'actions' in episode and isinstance(episode['actions'], (list, np.ndarray)):
                    total_samples += len(episode['actions'])
                else:
                    print(f"⚠️ Warning: Record with key {key.decode()} is missing 'actions' list.")
            except pickle.UnpicklingError:
                print(f"❌ CRITICAL ERROR: Failed to unpickle record with key {key.decode()}. The database may be corrupt at this location.")
                break
            except Exception as e:
                print(f"❌ CRITICAL ERROR: An unexpected error occurred reading key {key.decode()}: {e}")
                break

    print("\n" + "="*50)
    print("✅ Verification Complete!")
    print(f"  - Total Episodes: {total_episodes}")
    print(f"  - Total Samples (Timesteps): {total_samples}")
    print("="*50 + "\n")

    # Optional: Inspect a single episode's structure
    if inspect_idx >= 0:
        print(f"🔬 Inspecting structure of Episode #{inspect_idx}...")
        if inspect_idx >= total_episodes:
            print(f"❌ Error: Index {inspect_idx} is out of bounds. The database only has {total_episodes} episodes (0 to {total_episodes-1}).")
        else:
            with env.begin() as txn:
                key = f"{inspect_idx:08d}".encode("ascii")
                value = txn.get(key)
                if value is None:
                    print(f"❌ Error: Could not find record with key {key.decode()}.")
                else:
                    episode = pickle.loads(value)
                    print(f"  Episode Keys: {list(episode.keys())}\n")
                    for k, v in episode.items():
                        if isinstance(v, np.ndarray):
                            print(f"    - Key: '{k}', Type: numpy.ndarray, Shape: {v.shape}, Dtype: {v.dtype}")
                        elif isinstance(v, list):
                             # Check if list contains numpy arrays to show shape
                            if v and isinstance(v[0], np.ndarray):
                                print(f"    - Key: '{k}', Type: list of numpy.ndarray, Length: {len(v)}, Element Shape: {v[0].shape}")
                            else:
                                print(f"    - Key: '{k}', Type: list, Length: {len(v)}")
                        else:
                            print(f"    - Key: '{k}', Type: {type(v).__name__}, Value: {str(v)[:100]}")
        print("-" * 50 + "\n")

    env.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Inspect and verify an LMDB dataset.")
    parser.add_argument(
        "--db_path",
        type=Path,
        required=True,
        help="Path to the .lmdb file or directory to inspect."
    )
    parser.add_argument(
        "--inspect-episode",
        type=int,
        default=-1,
        help="Optional: The index of a single episode to print for detailed inspection."
    )
    args = parser.parse_args()

    inspect_database(args.db_path, args.inspect_episode)


"""
python -m s12 --db_path data\training\final_merged_dataset.lmdb
(venv) C:\Users\Hellx\Documents\Programming\python\Project\dgpo>python -m s12 --db_path data\training\final_merged_dataset.lmdb
🔍 Inspecting LMDB database at: data\training\final_merged_dataset.lmdb

Found 260 total episodes (records) in the database.
Verifying records and counting total samples...
100%|███████████████████████████████████████| 260/260 [01:09<00:00,  3.76it/s]

==================================================
✅ Verification Complete!
  - Total Episodes: 260
  - Total Samples (Timesteps): 67656
==================================================

"""